### ISSUE TITLE
Enable Monthly Update Subscription

### ISSUE THREAD

**Issue by jpgrace** [rust-osdev/homepage#200]
As a reader, I would like to have the monthly update emailed to me when it is ready. I would like a way to subscribe on the issue page.

**Comment by mvolfik** [comment]
+1. A low-tech solution would be to create a pinned Github Issues thread, lock it for comments only by moderators, and then every month when the update is published, some mod posts a link in that thread. Then anyone can easily subscribe to the "mailing list" with this button:
![image](https://github.com/rust-osdev/homepage/assets/31281386/23d42e15-f57d-4414-a6f4-a2e2c02297be)

**Comment by phil-opp** [comment]
Good idea! I created such an issue at https://github.com/rust-osdev/homepage/issues/212 .

**Comment by mvolfik** [comment]
the issue is not being updated :(

how are you creating the new page each month? What could you to remember to post an update here? If, for example, you always copy last month's page, maybe you could add a comment for yourself like `REMINDER: post to https://github.com/rust-osdev/homepage/issues/212 after publishing`

**Comment by IsaacWoods** [comment]
[Looks like Github has an API endpoint to create a comment in a given issue](https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#create-an-issue-comment). Rather than adding to the manual workload, I wonder if the publishing Action could automatically comment.

**Comment by mvolfik** [comment]
Right, I had no idea you had an Action for automatic publishing. It requires detecting that a new monthly page is being published in the given push, but it's possible. I created a PR in #249 - it's the bare minimum required to make this work, but I guess better a piece of sketchy automation than nothing?
